asset_path: /home/yhzhu/Industrial Robot/rob_ctrl_net/assets/abb_irb2400/urdf/irb2400.urdf
usd_dir: /home/yhzhu/Industrial Robot/rob_ctrl_net/assets/abb_irb2400/usd
usd_file_name: irb2400.usd
force_usd_conversion: true
make_instanceable: true
fix_base: true
root_link_name: null
link_density: 1000.0
merge_fixed_joints: true
convert_mimic_joints_to_normal_joints: false
joint_drive:
  drive_type: force
  target_type: none
  gains:
    stiffness: 0.0
    damping: 0.0
collider_type: convex_hull
self_collision: false
replace_cylinders_with_capsules: false
collision_from_visuals: false
func: isaaclab.sim.spawners.from_files.from_files:spawn_from_urdf
visible: true
semantic_tags: null
copy_from_source: true
mass_props: null
deformable_props: null
rigid_props: null
collision_props: null
activate_contact_sensors: false
scale: null
articulation_props: null
fixed_tendons_props: null
spatial_tendons_props: null
joint_drive_props: null
visual_material_path: material
visual_material: null
##
# Generated by UrdfConverter on 2025-12-31 at 11:46:17.
##
